### ISSUE TITLE
Data release?

### ISSUE THREAD

**Issue by Akhila-Yerukola** [meharbhatia/globalrg#1]
Hi! This is a cool work -- wanted to check when your dataset might be released? Thank you!

**Comment by meharbhatia** [comment]
Hi there. I am working on the data release and will email you shortly. 

Thank you for your interest.

**Comment by Akhila-Yerukola** [comment]
Hi @meharbhatia, following up on this to see if there is any update on the data release?

**Comment by MalvinaNikandrou** [comment]
Hi, I’m also really interested in exploring your dataset for some ongoing research. I was wondering if there’s been any progress on the data release or if you have an updated timeline? :smile:

**Comment by meharbhatia** [comment]
Hi @Akhila-Yerukola @MalvinaNikandrou 

The dataset is available here. 

GlobalRG Retrieval Across Universals (Task 1): https://huggingface.co/datasets/UBCNLP/GlobalRG-Retrieval

GlobalRG Cultural Visual Grounding (Task 2): https://huggingface.co/datasets/UBCNLP/GlobalRG-Grounding 

The dataset is currently under submission for a workshop task, we cannot release the ground-truth answers at this time. However, please fill out this form and I would be happy to provide you access. 
 
 https://forms.gle/mMHtmDWw64PzEsRNA
